module.exports = {
  'speed': [
    'pace',
    'rate',
    'velocity',
    'momentum',
    'tempo',
    'acceleration',
    'agility',
    'quickness',
    'activity',
    'alacrity',
    'breeze',
    'briskness',
    'rapidness',
    'readiness',
    'rush',
    'rustle',
    'snap',
    'steam',
    'swiftness',
    'urgency',
    'speediness',
    'race',
    'fly',
    'zoom',
    'zip',
    'break the speed',
    'drive too fast',
    'gear up',
    'hurry',
    'hustle',
    'run',
    'rush',
    'gather',
    'gear up',
    'get a move on',
    'get moving',
    'get under way',
    'go all out',
    'go fast',
    'go like the wind',
    'lose no time',
    'make haste',
    'open up',
    'throttle',
    'press on',
    'step on it'
  ],
  'decision': [
    'choice',
    'result',
    'conclusion',
    'verdict',
    'pronouncement',
    'judgement',
    'resolution',
    'assesment',
    'evaluation',
    'ruiling',
    'finding',
    'outcome',
    'decree',
    'accord',
    'agreement',
    'arrangement',
    'compromise',
    'determination',
    'decisiveness',
    'backbone',
    'doggedness',
    'earnestness',
    'grit',
    'obstinacy',
    'will power'
  ],
  'stink': [
    'fuss',
    'scandal',
    'smell',
    'stench',
    'horrible smell',
    'reek',
    'unpleasant odor',
    'pong',
    'whiff',
    'bad smell',
    'fetor',
    'foulness',
    'malodor',
    'noisomeness',
    'foul odor',
    'offensive smell',
    'smell horrible',
    'niff',
    'be rotten',
    'stink to high heaven',
    'uproar',
    'earnestness',
    'grit',
    'obstinacy',
    'will power'
  ],
  'screw': [
    'attach',
    'bolt',
    'fasten',
    'secure',
    'fix',
    'track',
    'nail',
    'turn',
    'twist',
    'rotate',
    'coil',
    'wind',
    'spin',
    'twist in tighten spiral',
    'twine',
    'work',
    'crumple',
    'distort',
    'contor',
    'crinkle',
    'fold',
    'scrunch',
    'crunch',
    'wrinkle',
    'furrow',
    'pucker',
    'contract',
    'crimp',
    'rumple',
    'rimple',
    'ruck up '
  ],
  'loose': [
    'movable',
    'slack',
    'wobly',
    'unfastaned',
    'free',
    'unattached',
    'baggy',
    'easy',
    'lax',
    'relaxed',
    'sloppy',
    'clear',
    'detached',
    'disconnected',
    'escaped',
    'floating',
    'hanging',
    'unbuttoned',
    'unclasped',
    'undone',
    'unhinge',
    'unhooked',
    'unlocked',
    'unpinned',
    'irresponsible',
    'careless',
    'weak',
    'abandoned',
    'corrupt',
    'debauched',
    'dissipated',
    'floppy',
    'supple',
    'droppy',
    'sagging'
  ],
  'hell': [
    'hades',
    'underworld',
    'netherworld',
    'perdition',
    'inferno',
    'abyss',
    'misery',
    'nightmare',
    'purgratory',
    'Gehhena Hades',
    'affliction',
    'agony',
    'anguish',
    'blazes',
    'difficulty',
    'grave',
    'limbo',
    'ordeal',
    'pandemonium',
    'pit',
    'suffering',
    'torment',
    'trial',
    'wretchedness',
    'Abaddon',
    'bottomless',
    'pit',
    'everlasting',
    'fire',
    'fire and brimstone',
    'hell-fire',
    'infernal regions',
    'lower world',
    'nether world',
    'place of torment'
  ],
  'baby': [
    'infant',
    'child',
    'newborn',
    'babe in arms',
    'tot',
    'little one',
    'kid',
    'chick',
    'toddler',
    'youngster',
    'bairn',
    'bambino',
    'bundle',
    'buttercup',
    'button',
    'cherub',
    'crawler',
    'deduction',
    'dividend',
    'dumpling',
    'nipper',
    'nursling',
    'papoose',
    'preemie',
    'suckling',
    'tad',
    'write-off',
    'angelface',
    'little angel',
    'little darling',
    'little doll',
    'miniature',
    'diminutive'
  ],
  'rude': [
    'impolite',
    'discourteous',
    'bad-mannered',
    'insolent',
    'uncouth',
    'offensive',
    'ill-mannered',
    'vulgar',
    'boorish',
    'disrespectful',
    'rough',
    'abusive',
    'blunt',
    'coarse',
    'crude',
    'ignorant',
    'insulting',
    'intrusive',
    'obscene',
    'surly',
    'uncivil',
    'abrupt',
    'barbarian',
    'barbaric',
    'barbarous',
    'brusque',
    'brutish',
    'cheeky',
    'churlish',
    'crabbed',
    'curt',
    'graceless',
    'gross',
    'gruff',
    'illiterate',
    'impertinent',
    'impudent',
    'inconsiderate',
    'loutish',
    'low',
    'offhand',
    'peremptory',
    'raw',
    'savage',
    'scurrilous',
    'short',
    'uncivilized',
    'uncultured',
    'uneducated',
    'ungracious',
    'unmannerly',
    'unpolished',
    'unrefined',
    'wild',
    'foul',
    'foul-mouthed',
    'indecent'
  ],
  'horn': [
    'siren',
    'klaxon',
    'hooter',
    'alarm',
    'buzzer',
    'bleeper',
    'alert',
    'signaling',
    'device',
    'caution',
    'cry',
    'signal',
    'warning',
    'whistle',
    'Mayday SOS',
    'bell',
    'blast',
    'call',
    'clock',
    'drum',
    'flap',
    'flash',
    'forewarning',
    'gong',
    'nod',
    'scramble',
    'scream',
    'shout',
    'sign',
    'squeal',
    'tip',
    'tocsin',
    'trumpet',
    'wink',
    'yell',
    'high',
    'sign',
    'tip off',
    'antler',
    'spine',
    'barb',
    'projection',
    'tusk',
    'point',
    'spike',
    'fork',
    'hook',
    'nib',
    'spur',
    'tine'
  ],
  'phoney': [
    'hypocrite', 'cardboard', 'hypocritical'
  ],
  'sob': [
    'moan',
    'cry',
    'weep',
    'snivel',
    'sniffle',
    'sniff',
    'snuffle',
    'shed tears',
    'tears',
    'blub',
    'bawl',
    'howl',
    'blubber',
    'cry hard',
    'break down',
    'wail',
    'whimper',
    'lament',
    'boohoo',
    'cry a river',
    'cry convulsively',
    'cry eyes out',
    'turn on waterworks',
    'wailing',
    'waterworks',
    'mew',
    'plaintive cry',
    'lamentation',
    'sob act',
    'groan',
    'shedding tears',
    'the blues',
    'whine',
    'keening',
    'moan',
    'plaint',
    'teardrop'
  ],
  'at': [
    'on',
    'next to',
    'by the side of',
    'by appearing in',
    'found in',
    'in the vicinity of',
    'near to',
    'placed at',
    'situated at',
    'through',
    'toward',
    'leaning on',
    'on',
    'up on',
    'closes to',
    'along',
    'on top of',
    'resting on',
    'situated on'
  ],
  'swing': [
    'swipe',
    'slap',
    'punch',
    'thump',
    'blow',
    'strike',
    'smack',
    'fluctuation',
    'rhythm',
    'stroke',
    'beat',
    'cadence',
    'cadency',
    'lilt',
    'measure',
    'meter',
    'motion',
    'oscillation',
    'sway',
    'swaying',
    'tempo',
    'undulation',
    'vibration',
    'fluctuate',
    'sway',
    'rock',
    'roll',
    'move back and forth',
    'move backwards and forwards',
    'oscillate',
    'change',
    'vacillate',
    'alter',
    'alternate',
    'shift',
    'turn around',
    'spin around',
    'swivel around',
    'whirl around',
    'veer',
    'move to',
    'curve',
    'dangle',
    'flap',
    'hang',
    'lurch',
    'pitch',
    'pivot',
    'rotate',
    'swivel',
    'turn',
    'twirl',
    'wave',
    'whirl',
    'wiggle',
    'wobble',
    'avert',
    'deflect',
    'divert',
    'palpitate',
    'reel',
    'revolve',
    'sheer',
    'shunt',
    'suspend'
  ],
  'stroke': [
    'rub', 'caress', 'fondle', 'pat'
  ],
  'score': [
    'keep count',
    'keep a tally',
    'keep score',
    'count',
    'tot up',
    'record',
    'add',
    'tally',
    'calculate',
    'enumerate',
    'reckon',
    'register',
    'total',
    'keep tally',
    'etch',
    'carve'
  ],
  'prick': [
    'hole', 'puncture', 'perforate', 'jab', 'prickle'
  ],
  'hot': [
    'warm',
    'burning',
    'scorching',
    'boiling',
    'blistering',
    'sizzling',
    'searching',
    'broiling',
    'fiery',
    'heat',
    'scalding',
    'blazing',
    'sultry',
    'sweltering',
    'torrid',
    'tropical',
    'baking',
    'close',
    'fevered',
    'feverish',
    'feverous',
    'flaming',
    'ingenous',
    'like an oven',
    'on fire',
    'ovenlike',
    'parching',
    'piping',
    'roasting',
    'very warm '
  ],
  'suck': [
    'slurp',
    'draw',
    'pull',
    'drink',
    'extract',
    'absorb',
    'inhale',
    'suction'
  ]
}
